
package com.mixamus.client.ws.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Demo", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Demo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hi", targetNamespace = "http://ws/", className = "com.mixamus.client.ws.demo.Hi")
    @ResponseWrapper(localName = "hiResponse", targetNamespace = "http://ws/", className = "com.mixamus.client.ws.demo.HiResponse")
    @Action(input = "http://ws/Demo/hiRequest", output = "http://ws/Demo/hiResponse")
    public String hi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://ws/", className = "com.mixamus.client.ws.demo.HelloWorld")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://ws/", className = "com.mixamus.client.ws.demo.HelloWorldResponse")
    @Action(input = "http://ws/Demo/helloWorldRequest", output = "http://ws/Demo/helloWorldResponse")
    public String helloWorld();

}
